# Generated by Django 4.0.2 on 2022-02-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restapi',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=255)),
            ],
        ),
    ]
